"""Register the app to launch automatically when the user logs in.

Everything here writes inside the user's own profile — no administrator rights,
no system-wide services:

* Windows — a hidden-launch ``.vbs`` in the Startup folder.
* macOS   — a LaunchAgent plist in ``~/Library/LaunchAgents``.
* Linux   — a systemd *user* unit, falling back to an XDG autostart ``.desktop``.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

LABEL = "io.github.resendegu.tiquetaque-sync"
UNIT_NAME = "tiquetaque-sync"
DISPLAY_NAME = "TiqueTaque Sync"


class AutostartError(RuntimeError):
    """Raised when the autostart entry cannot be created or removed."""


@dataclass
class AutostartStatus:
    enabled: bool
    supported: bool
    mechanism: str
    location: str | None = None
    detail: str | None = None

    def to_dict(self) -> dict:
        return {
            "enabled": self.enabled,
            "supported": self.supported,
            "mechanism": self.mechanism,
            "location": self.location,
            "detail": self.detail,
        }


# ------------------------------------------------------------------------------
# Launch command resolution
# ------------------------------------------------------------------------------
def is_frozen() -> bool:
    """True quando rodando dentro do executável empacotado (PyInstaller)."""
    return bool(getattr(sys, "frozen", False))


def _launch_command(windowless: bool = False) -> list[str]:
    """Build the command line that starts the background service.

    Três cenários, nesta ordem:
    1. Executável congelado (.exe): re-invoca a si mesmo com argumentos.
    2. Instalado via pip: usa o console script do PATH.
    3. Checkout do código-fonte: cai para ``python -m tiquetaque_sync``.
    """
    if is_frozen():
        return [sys.executable, "start", "--no-browser"]

    script_name = "tiquetaque-syncw" if windowless else "tiquetaque-sync"
    console_script = shutil.which(script_name)
    if console_script:
        return [console_script, "start", "--no-browser"]

    python = sys.executable
    if windowless and sys.platform == "win32":
        pythonw = Path(python).with_name("pythonw.exe")
        if pythonw.exists():
            python = str(pythonw)
    return [python, "-m", "tiquetaque_sync", "start", "--no-browser"]


def _launch_workdir() -> str | None:
    """Working directory required by the ``python -m`` fallback.

    When the package is not installed (source checkout), the module is only
    importable with the repository root as the working directory. O executável
    congelado carrega tudo dentro de si, então não precisa de nada.
    """
    if is_frozen() or shutil.which("tiquetaque-sync") or shutil.which("tiquetaque-syncw"):
        return None
    return str(Path(__file__).resolve().parent.parent)


def _quote(arg: str) -> str:
    return f'"{arg}"' if " " in arg else arg


# ------------------------------------------------------------------------------
# Windows — Startup folder
# ------------------------------------------------------------------------------
def _windows_entry() -> Path:
    appdata = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
    startup = Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
    return startup / "TiqueTaqueSync.vbs"


def _windows_enable() -> AutostartStatus:
    entry = _windows_entry()
    entry.parent.mkdir(parents=True, exist_ok=True)
    command = " ".join(_quote(part) for part in _launch_command(windowless=True))
    workdir = _launch_workdir()

    lines = [
        "' Generated by TiqueTaque Sync - do not edit",
        'Set sh = CreateObject("WScript.Shell")',
    ]
    if workdir:
        lines.append(f'sh.CurrentDirectory = "{workdir}"')
    # Run style 0 = hidden window, False = do not wait for the process to exit.
    lines.append('sh.Run "%s", 0, False' % command.replace('"', '""'))
    entry.write_text("\r\n".join(lines) + "\r\n", encoding="utf-8")
    return _windows_status()


def _windows_disable() -> AutostartStatus:
    entry = _windows_entry()
    if entry.exists():
        entry.unlink()
    return _windows_status()


def _windows_status() -> AutostartStatus:
    entry = _windows_entry()
    return AutostartStatus(
        enabled=entry.exists(),
        supported=True,
        mechanism="Pasta Inicializar do Windows",
        location=str(entry) if entry.exists() else None,
    )


# ------------------------------------------------------------------------------
# macOS — LaunchAgent
# ------------------------------------------------------------------------------
def _macos_entry() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def _macos_enable() -> AutostartStatus:
    entry = _macos_entry()
    entry.parent.mkdir(parents=True, exist_ok=True)
    args = "".join(f"        <string>{part}</string>\n" for part in _launch_command())
    workdir = _launch_workdir()
    workdir_key = (
        f"    <key>WorkingDirectory</key>\n    <string>{workdir}</string>\n" if workdir else ""
    )
    entry.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        "<dict>\n"
        f"    <key>Label</key>\n    <string>{LABEL}</string>\n"
        "    <key>ProgramArguments</key>\n    <array>\n"
        f"{args}"
        "    </array>\n"
        f"{workdir_key}"
        "    <key>RunAtLoad</key>\n    <true/>\n"
        "    <key>KeepAlive</key>\n    <false/>\n"
        "</dict>\n</plist>\n",
        encoding="utf-8",
    )
    _run(["launchctl", "load", "-w", str(entry)], check=False)
    return _macos_status()


def _macos_disable() -> AutostartStatus:
    entry = _macos_entry()
    if entry.exists():
        _run(["launchctl", "unload", "-w", str(entry)], check=False)
        entry.unlink()
    return _macos_status()


def _macos_status() -> AutostartStatus:
    entry = _macos_entry()
    return AutostartStatus(
        enabled=entry.exists(),
        supported=True,
        mechanism="LaunchAgent do macOS",
        location=str(entry) if entry.exists() else None,
    )


# ------------------------------------------------------------------------------
# Linux — systemd user unit, falling back to XDG autostart
# ------------------------------------------------------------------------------
def _systemd_unit() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "systemd" / "user" / f"{UNIT_NAME}.service"


def _xdg_entry() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "autostart" / f"{UNIT_NAME}.desktop"


def _has_systemd() -> bool:
    return shutil.which("systemctl") is not None


def _linux_enable() -> AutostartStatus:
    command = " ".join(_quote(part) for part in _launch_command())
    workdir = _launch_workdir()

    if _has_systemd():
        unit = _systemd_unit()
        unit.parent.mkdir(parents=True, exist_ok=True)
        unit.write_text(
            "[Unit]\n"
            f"Description={DISPLAY_NAME} — monitor de jornada\n"
            "After=network-online.target\n\n"
            "[Service]\n"
            "Type=simple\n"
            + (f"WorkingDirectory={workdir}\n" if workdir else "")
            + f"ExecStart={command}\n"
            "Restart=on-failure\n"
            "RestartSec=10\n\n"
            "[Install]\n"
            "WantedBy=default.target\n",
            encoding="utf-8",
        )
        _run(["systemctl", "--user", "daemon-reload"], check=False)
        result = _run(["systemctl", "--user", "enable", "--now", f"{UNIT_NAME}.service"], check=False)
        if result.returncode != 0:
            raise AutostartError(
                f"systemctl --user enable falhou: {result.stderr.strip() or result.stdout.strip()}"
            )
        return _linux_status()

    entry = _xdg_entry()
    entry.parent.mkdir(parents=True, exist_ok=True)
    entry.write_text(
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={DISPLAY_NAME}\n"
        f"Exec={command}\n"
        + (f"Path={workdir}\n" if workdir else "")
        + "Terminal=false\n"
        "X-GNOME-Autostart-enabled=true\n",
        encoding="utf-8",
    )
    return _linux_status()


def _linux_disable() -> AutostartStatus:
    if _has_systemd() and _systemd_unit().exists():
        _run(["systemctl", "--user", "disable", "--now", f"{UNIT_NAME}.service"], check=False)
        _systemd_unit().unlink()
        _run(["systemctl", "--user", "daemon-reload"], check=False)

    entry = _xdg_entry()
    if entry.exists():
        entry.unlink()
    return _linux_status()


def _linux_status() -> AutostartStatus:
    if _has_systemd():
        unit = _systemd_unit()
        if unit.exists():
            return AutostartStatus(
                enabled=True,
                supported=True,
                mechanism="Serviço systemd do usuário",
                location=str(unit),
            )

    entry = _xdg_entry()
    return AutostartStatus(
        enabled=entry.exists(),
        supported=True,
        mechanism="Serviço systemd do usuário" if _has_systemd() else "Autostart XDG",
        location=str(entry) if entry.exists() else None,
    )


def _run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


# ------------------------------------------------------------------------------
# Public API
# ------------------------------------------------------------------------------
def launch_command(windowless: bool = False) -> list[str]:
    """Comando que sobe o serviço em background (usado pela GUI e pelos atalhos)."""
    return _launch_command(windowless=windowless)


def launch_workdir() -> str | None:
    """Diretório de trabalho exigido pelo fallback ``python -m`` (checkout)."""
    return _launch_workdir()


def status() -> AutostartStatus:
    if sys.platform == "win32":
        return _windows_status()
    if sys.platform == "darwin":
        return _macos_status()
    if sys.platform.startswith("linux"):
        return _linux_status()
    return AutostartStatus(
        enabled=False,
        supported=False,
        mechanism="indisponível",
        detail=f"Plataforma {sys.platform} não suportada para autostart.",
    )


def enable() -> AutostartStatus:
    if sys.platform == "win32":
        return _windows_enable()
    if sys.platform == "darwin":
        return _macos_enable()
    if sys.platform.startswith("linux"):
        return _linux_enable()
    raise AutostartError(f"Autostart não suportado em {sys.platform}.")


def disable() -> AutostartStatus:
    if sys.platform == "win32":
        return _windows_disable()
    if sys.platform == "darwin":
        return _macos_disable()
    if sys.platform.startswith("linux"):
        return _linux_disable()
    raise AutostartError(f"Autostart não suportado em {sys.platform}.")


def set_enabled(value: bool) -> AutostartStatus:
    return enable() if value else disable()
